mydjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

# URL의 구분을 위해서 URLconf에 namespace를 추가해 준다.
app_name = 'polls'
urlpatterns = [
    # 제네릭 뷰
    path('', views.IndexView.as_view(), name='index'),
    path('/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('/<int:pk>/results', views.ResultsView.as_view(), name='results'),
    path('/<int:question_id>/vote', views.vote, name='vote'),

    # path('', views.index, name='index'),
    # path('/<int:question_id>/', views.detail, name='detail'),
    # path('/<int:question_id>/results/', views.results, name='results'),
    # path('/<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# __str__ 메소드는 django 가 자동으로 생성하는 관리사이트에서도 객체의 표현이 사용되기 때문
# 시간대 조작에 대해 더 잘 알고싶다면 https://docs.djangoproject.com/ko/4.0/topics/i18n/timezones/


class Question(models.Model):
    question_text = models.CharField(max_length=200)  # 질문
    pub_date = models.DateTimeField('date published')  # 발행일

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        #return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        # datetime.timedelta 를 통해 days라는 인수에 값을 넣어 지금으로부터 인수값 만큼 지난 날을 얻는다.


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)  # 선택 텍스트
    votes = models.IntegerField(default=0)  # 투표 집계

    def __str__(self):
        return self.choice_text


# 데이터베이스의 각 필드는 Field 클래스의 인스턴스로서 표현된다. CharField는 문자 필드를 표현하고,
# DataTimeField는 날짜와 시간의 필드를 표현한다(datetime).
# ForeignKey 를 사용한 관계설정
# 각각의 Choice가 하나의 Question에 관계된다는 것을 알려준다.
# 다 대 일, 다 대 다, 일 대 일
# 모든 일반 데이터베이스와 관계들을 지원한다.

# python manage.py makemigrations 를 통해 변경사항에 대한 마이그레이션 생성
# python manage.py migrate 명령을 통해 변경사항을 데이터베이스에 적용 (git add, commit같음)

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

{#<h1>{{ question.question_text }}</h1>#}
{#<ul>#}
{#    {% for choice in question.choice_set.all %}#}
{#        <li>{{ choice.choice_text }}</li>#}
{#    {% endfor %}#}
{#</ul>#}
<!-- 템플릿에 대한 자세한 정보 ->  https://docs.djangoproject.com/ko/4.0/topics/templates/ -->

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <!--하드코딩 되어있는 url-->
{#        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>#}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>